# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac36229aecf6be9ae2003fdde5f0bbedf380c5db23ba7b73a882dc4d0ee7ff5309c85dc06a7f33f33f832d68149547e6bf5c9eab1af4b26f10d3b254cb199211

test:
  secret_key_base: c01398cfe7199738139f2384d07f848eefeeaaf0886fcd11a769c8437db347c4d32b1890d882666b27947dffef273c33f799068f91684dfb2e0a8b6ab6aa713b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
